name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # --- JOB 1: Build & Smoke test ---
  node-ci:
    name: Build & Smoke Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install deps
        run: npm install

      - name: Typecheck (tsc)
        run: npx tsc --noEmit

      - name: Build
        run: npm run build

      - name: Pre-reqs jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Smoke test CLI
        shell: bash
        run: |
          set -e
          node dist/cli/index.js auth:register -e ci@example.com -p "S3gura!2024" -r user
          node dist/cli/index.js auth:login -e ci@example.com -p "S3gura!2024"
          if [ -f logs/audit.log ]; then
            SID=$(tail -n 1 logs/audit.log | jq -r '.sessionId // empty')
            if [ -n "$SID" ] && [ "$SID" != "null" ]; then
              node dist/cli/index.js auth:logout --session "$SID"
            fi
          fi

      - name: Publicar artefactos (logs y data)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-logs-${{ matrix.node-version }}
          path: |
            logs/**
            data/**

  # --- JOB 2: CodeQL Security Scan ---
  codeql:
    name: CodeQL Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: github/codeql-action/init@v3
        with:
          languages: javascript-typescript

      - uses: github/codeql-action/autobuild@v3

      - uses: github/codeql-action/analyze@v3



