name: Release

on:
  push:
    tags: ['v*']           # como ahora
  release:
    types: [published]     # si creas un Release desde la UI
  workflow_dispatch:       # botón “Run workflow” manual

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Detectar si existe lockfile (package-lock.json / npm-shrinkwrap.json / yarn.lock)
      - name: Detect lockfile
        id: detect-lock
        shell: bash
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ] || [ -f yarn.lock ]; then
            echo "has_lock=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_lock=false" >> "$GITHUB_OUTPUT"
          fi

      # Setup Node con cache SOLO si hay lockfile
      - name: Use Node (with cache)
        if: steps.detect-lock.outputs.has_lock == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      # Setup Node SIN cache si no hay lockfile
      - name: Use Node (no cache)
        if: steps.detect-lock.outputs.has_lock != 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # Instalar dependencias (ci con lockfile, install sin lockfile)
      - name: Install deps (npm ci)
        if: steps.detect-lock.outputs.has_lock == 'true'
        run: npm ci

      - name: Install deps (npm install)
        if: steps.detect-lock.outputs.has_lock != 'true'
        run: npm install

      - name: Typecheck
        run: npx tsc --noEmit

      - name: Build
        run: npm run build

      - name: Empaquetar dist
        run: |
          tar -czf dist.tar.gz dist package.json README.md

      - name: Crear Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}            # usa el tag que disparó el flujo (vX.Y.Z)
          name: ${{ github.ref_name }}           # nombre del release = tag
          draft: false
          prerelease: false

