name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Empaquetar dist
        run: |
          tar -czf dist.tar.gz dist package.json README.md

      - name: Crear Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
